### ISSUE TITLE
`Desync` has unsound variance

### ISSUE THREAD

**Issue by LegionMammal978** [Logicalshift/desync#6]
Since a `Desync<T>` stores its `T` in a `Box`, it is covariant over `T`. However, this is unsound, since it allows exclusive (`&mut`) access to its `T` through shared (`&`) references; in other words, it is an interior mutability type. To illustrate the issue, this function can convert any reference into a `'static` reference:
```rust
use desync::Desync;

fn make_static<T: ?Sized>(v: &T) -> &'static T {
    let d1: Desync<Option<fn(&T) -> &'static T>> = Desync::new(None);
    let d2: &Desync<Option<fn(&T) -> &T>> = &d1;
    d2.sync(|f| *f = Some(|v| v));
    d1.sync(|f| f.unwrap())(v)
}
```

The fix is to make `Desync<T>` invariant over `T`. This can be done most simply by adding a `PhantomData<fn(&mut T)>` (or equivalent) to the `Desync` struct. However, the current implementation of `Desync` breaks Rust's aliasing rules in a few different ways, and I'm currently preparing a PR which should fix this issue alongside the aliasing issues, so you might prefer to wait for that.

**Comment by Logicalshift** [comment]
Ah, yes, I see. Good spot, I'd completely overlooked this for years. It's actually a little surprising to me that Pin<Box<...>> works that way.

Looks like an UnsafeCell might be a better approach than PhantomData? It makes it much more explicit that interior mutability is occurring.
